added the carousel
Hack-Weekly/bronze-badger-recipe-app pull request #11
Opened 2023-07-03 07:04 UTC by cod3-craft3r

I tried adding transition but it breaks, so currently I've removed them.

2023-07-03 21:44 UTC, Rmichal503 requested changes

2023-07-03 21:44 UTC, Rmichal503 commented on src/components/Footer.component.jsx
remove this file from PR

2023-07-03 21:44 UTC, Rmichal503 commented on src/components/Carousel.component.jsx
Carousel works, there is issue with timer, would be worth adding `height` of whole component

2023-07-03 21:44 UTC, Rmichal503 commented on src/components/Carousel.component.jsx
> +import React, { useState, useEffect, Fragment } from "react";
You use `<Fragment>` nowhere

2023-07-03 21:44 UTC, Rmichal503 commented on src/App.jsx
discard any changes, and remove this file from PR

2023-07-04 05:46 UTC, cod3-craft3r commented on src/components/Carousel.component.jsx
it takes the height of the images dynamically, but this would force us to use images of same dimensions (but i feel that won't be a problem since it'll only help in consistency)

2023-07-04 05:47 UTC, cod3-craft3r commented on src/components/Carousel.component.jsx
if you guys still want me to add a height to it, I'll do it

2023-07-04 05:47 UTC, cod3-craft3r commented on src/components/Carousel.component.jsx
> +import React, { useState, useEffect, Fragment } from "react";
I removed it

2023-07-04 05:47 UTC, cod3-craft3r commented on src/App.jsx
done

2023-07-04 05:48 UTC, closed without merging